version: '3.0'

services:

  ignite:
    image: apacheignite/ignite
    ports:
      - "11211:11211"
      - "47100:47100"
      - "47500:47500"
      - "49112:49112"
      - "8080:8080"
    environment:
      OPTION_LIBS: "ignite-rest-http"